// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_children_url`, `new`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CreateFolderRequest`, `CreateFolderResponse`, `DriveFileFacet`, `DriveFolderFacet`, `FolderFacet`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// 在指定目录下创建文件夹。
Future<DriveItemSummary> createDriveFolder({
  required String name,
  String? parentId,
  String? parentPath,
  String? conflictBehavior,
}) => RustLib.instance.api.crateApiDriveCreateFolderCreateDriveFolder(
  name: name,
  parentId: parentId,
  parentPath: parentPath,
  conflictBehavior: conflictBehavior,
);
