// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BatchDeletePayload`, `BatchDeleteRequest`, `BatchDeleteResponsePayload`, `BatchDeleteResponse`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseNotAllowedOwner): `is_success`

/// 删除指定的 drive item（移动到回收站），可选携带 If-Match 与 bypass 锁。
Future<void> deleteDriveItem({
  required String itemId,
  String? ifMatch,
  required bool bypassLocks,
}) => RustLib.instance.api.crateApiDriveDeleteDeleteDriveItem(
  itemId: itemId,
  ifMatch: ifMatch,
  bypassLocks: bypassLocks,
);

/// 批量删除 drive items（移动到回收站），最多 20 项。
/// 返回删除失败的 item ids。
Future<List<String>> deleteDriveItemsBatch({
  required List<String> itemIds,
  required bool bypassLocks,
}) => RustLib.instance.api.crateApiDriveDeleteDeleteDriveItemsBatch(
  itemIds: itemIds,
  bypassLocks: bypassLocks,
);

abstract class HttpStatusExt {
  Future<bool> isSuccess();
}
