// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 删除指定的 drive item（移动到回收站），可选携带 If-Match 与 bypass 锁。
Future<void> deleteDriveItem({
  required String itemId,
  String? ifMatch,
  required bool bypassLocks,
}) => RustLib.instance.api.crateApiDriveDeleteDeleteDriveItem(
  itemId: itemId,
  ifMatch: ifMatch,
  bypassLocks: bypassLocks,
);
