// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DriveFileFacetDto`, `DriveFolderFacetDto`, `DriveItemDetailsDto`, `FileSystemInfoDto`, `ParentReferenceDto`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

/// 获取单个 drive item 的完整属性，用于属性面板显示。
Future<DriveItemDetails> getDriveItemDetails({required String itemId}) =>
    RustLib.instance.api.crateApiDriveDetailsGetDriveItemDetails(
      itemId: itemId,
    );
