// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<DownloadQueueState> downloadQueueState() =>
    RustLib.instance.api.crateApiDriveDownloadManagerDownloadQueueState();

Future<DownloadQueueState> enqueueDownloadTask({
  required DriveItemSummary item,
  required String targetDir,
  required bool overwrite,
}) => RustLib.instance.api.crateApiDriveDownloadManagerEnqueueDownloadTask(
  item: item,
  targetDir: targetDir,
  overwrite: overwrite,
);

Future<DownloadQueueState> removeDownloadTask({required String itemId}) =>
    RustLib.instance.api.crateApiDriveDownloadManagerRemoveDownloadTask(
      itemId: itemId,
    );

Future<DownloadQueueState> clearDownloadHistory() =>
    RustLib.instance.api.crateApiDriveDownloadManagerClearDownloadHistory();

Stream<DownloadProgressUpdate> downloadProgressStream() =>
    RustLib.instance.api.crateApiDriveDownloadManagerDownloadProgressStream();
