// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `fetch_download_metadata`, `prepare_destination`, `sanitize_file_name`, `stream_download`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DriveFileFacet`, `DriveItemDownloadDto`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`

Future<DriveDownloadResult> downloadDriveItem({
  required String itemId,
  required String targetDir,
  required bool overwrite,
}) => RustLib.instance.api.crateApiDriveDownloadDownloadDriveItem(
  itemId: itemId,
  targetDir: targetDir,
  overwrite: overwrite,
);
