// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `add_progress_sink`, `broadcast_update`, `clear_history_from_storage`, `clear_history`, `clear_progress_meter`, `compute_speed_bps`, `emit_progress_snapshot`, `enqueue_internal`, `mark_failure`, `mark_success`, `new`, `now_millis`, `opt_i64_to_u64`, `opt_u64_to_i64`, `persist_task`, `prune_inactive_meters`, `record_from_task`, `remove_task_from_storage`, `remove_task`, `report_progress`, `restore_from_storage`, `shared`, `snapshot`, `status_from_i64`, `status_to_i64`, `task_from_record`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DownloadManager`, `InnerState`, `ProgressTick`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `from`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`

Future<DownloadQueueState> downloadQueueState() =>
    RustLib.instance.api.crateApiDriveDownloadManagerDownloadQueueState();

Future<DownloadQueueState> enqueueDownloadTask({
  required DriveItemSummary item,
  required String targetDir,
  required bool overwrite,
}) => RustLib.instance.api.crateApiDriveDownloadManagerEnqueueDownloadTask(
  item: item,
  targetDir: targetDir,
  overwrite: overwrite,
);

Future<DownloadQueueState> removeDownloadTask({required String itemId}) =>
    RustLib.instance.api.crateApiDriveDownloadManagerRemoveDownloadTask(
      itemId: itemId,
    );

Future<DownloadQueueState> clearDownloadHistory() =>
    RustLib.instance.api.crateApiDriveDownloadManagerClearDownloadHistory();

Stream<DownloadProgressUpdate> downloadProgressStream() =>
    RustLib.instance.api.crateApiDriveDownloadManagerDownloadProgressStream();
