// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `clear_history`, `enqueue_internal`, `mark_failure`, `mark_success`, `new`, `now_millis`, `remove_task`, `shared`, `snapshot`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DownloadManager`, `InnerState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `from`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`

Future<DownloadQueueState> downloadQueueState() =>
    RustLib.instance.api.crateApiDriveDownloadManagerDownloadQueueState();

Future<DownloadQueueState> enqueueDownloadTask({
  required DriveItemSummary item,
  required String targetDir,
  required bool overwrite,
}) => RustLib.instance.api.crateApiDriveDownloadManagerEnqueueDownloadTask(
  item: item,
  targetDir: targetDir,
  overwrite: overwrite,
);

Future<DownloadQueueState> removeDownloadTask({required String itemId}) =>
    RustLib.instance.api.crateApiDriveDownloadManagerRemoveDownloadTask(
      itemId: itemId,
    );

Future<DownloadQueueState> clearDownloadHistory() =>
    RustLib.instance.api.crateApiDriveDownloadManagerClearDownloadHistory();
