// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_children_url_for_folder`, `build_gallery_children_url`, `fetch_gallery_page_filtered`, `has_image_extension`, `is_gallery_image_item`, `scan_gallery_items_from_root`

/// 拉取图库（photos special folder）中的图片项，支持分页。
///
/// Graph 的 photos 目录可能包含视频等非图片条目，这里会在 Rust 侧过滤后再返回给 UI。
/// 当某一页全部被过滤掉时，会自动继续向后读取最多若干页，避免前端出现“空白分页”。
Future<DrivePage> listDriveGalleryItems({String? nextLink, int? top}) => RustLib
    .instance
    .api
    .crateApiDriveGalleryListDriveGalleryItems(nextLink: nextLink, top: top);
