// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `from_identity_set`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DriveInfoDto`, `DriveQuotaDto`, `IdentityDto`, `IdentitySetDto`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`, `fmt`, `fmt`, `from`

/// 获取当前用户的 OneDrive 概览信息（包含配额与所有者）。
/// - 请求：`GET /me/drive?$select=id,driveType,owner,quota`
/// - 若 OneDrive 未开通或不可用，返回明确的错误提示。
Future<DriveInfo> getDriveOverview() =>
    RustLib.instance.api.crateApiDriveInfoGetDriveOverview();
