// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `best_url`, `build_children_url`, `fetch_drive_children`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DriveChildrenResponse`, `DriveFolderFacet`, `DriveItemDto`, `ThumbnailDto`, `ThumbnailSetDto`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

Future<DrivePage> listDriveChildren({
  String? folderId,
  String? folderPath,
  String? nextLink,
}) => RustLib.instance.api.crateApiDriveListListDriveChildren(
  folderId: folderId,
  folderPath: folderPath,
  nextLink: nextLink,
);
