// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

class DriveDownloadResult {
  final String fileName;
  final String savedPath;
  final BigInt bytesDownloaded;
  final BigInt? expectedSize;

  const DriveDownloadResult({
    required this.fileName,
    required this.savedPath,
    required this.bytesDownloaded,
    this.expectedSize,
  });

  @override
  int get hashCode =>
      fileName.hashCode ^
      savedPath.hashCode ^
      bytesDownloaded.hashCode ^
      expectedSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DriveDownloadResult &&
          runtimeType == other.runtimeType &&
          fileName == other.fileName &&
          savedPath == other.savedPath &&
          bytesDownloaded == other.bytesDownloaded &&
          expectedSize == other.expectedSize;
}

class DriveItemSummary {
  final String id;
  final String name;
  final BigInt? size;
  final bool isFolder;
  final PlatformInt64? childCount;
  final String? mimeType;
  final String? lastModified;
  final String? thumbnailUrl;

  const DriveItemSummary({
    required this.id,
    required this.name,
    this.size,
    required this.isFolder,
    this.childCount,
    this.mimeType,
    this.lastModified,
    this.thumbnailUrl,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      size.hashCode ^
      isFolder.hashCode ^
      childCount.hashCode ^
      mimeType.hashCode ^
      lastModified.hashCode ^
      thumbnailUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DriveItemSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          size == other.size &&
          isFolder == other.isFolder &&
          childCount == other.childCount &&
          mimeType == other.mimeType &&
          lastModified == other.lastModified &&
          thumbnailUrl == other.thumbnailUrl;
}

class DrivePage {
  final List<DriveItemSummary> items;
  final String? nextLink;

  const DrivePage({required this.items, this.nextLink});

  @override
  int get hashCode => items.hashCode ^ nextLink.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DrivePage &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          nextLink == other.nextLink;
}
