// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// 下载进度事件，通过 StreamSink 推送给 Flutter，供 UI 实时刷新进度与速度。
class DownloadProgressUpdate {
  final String itemId;
  final BigInt bytesDownloaded;
  final BigInt? expectedSize;
  final double? speedBps;
  final PlatformInt64 timestampMillis;

  const DownloadProgressUpdate({
    required this.itemId,
    required this.bytesDownloaded,
    this.expectedSize,
    this.speedBps,
    required this.timestampMillis,
  });

  @override
  int get hashCode =>
      itemId.hashCode ^
      bytesDownloaded.hashCode ^
      expectedSize.hashCode ^
      speedBps.hashCode ^
      timestampMillis.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DownloadProgressUpdate &&
          runtimeType == other.runtimeType &&
          itemId == other.itemId &&
          bytesDownloaded == other.bytesDownloaded &&
          expectedSize == other.expectedSize &&
          speedBps == other.speedBps &&
          timestampMillis == other.timestampMillis;
}

/// 下载队列状态，包含进行中、已完成与失败任务列表。
class DownloadQueueState {
  final List<DownloadTask> active;
  final List<DownloadTask> completed;
  final List<DownloadTask> failed;

  const DownloadQueueState({
    required this.active,
    required this.completed,
    required this.failed,
  });

  static Future<DownloadQueueState> default_() =>
      RustLib.instance.api.crateApiDriveModelsDownloadQueueStateDefault();

  @override
  int get hashCode => active.hashCode ^ completed.hashCode ^ failed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DownloadQueueState &&
          runtimeType == other.runtimeType &&
          active == other.active &&
          completed == other.completed &&
          failed == other.failed;
}

/// 下载任务状态，迁移至 Rust 端统一管理。
enum DownloadStatus { inProgress, completed, failed }

/// 单条下载任务详情，供 Flutter 展示进度与历史。
class DownloadTask {
  final DriveItemSummary item;
  final DownloadStatus status;
  final PlatformInt64 startedAt;
  final PlatformInt64? completedAt;
  final String? savedPath;
  final BigInt? sizeLabel;
  final BigInt? bytesDownloaded;
  final String? errorMessage;

  const DownloadTask({
    required this.item,
    required this.status,
    required this.startedAt,
    this.completedAt,
    this.savedPath,
    this.sizeLabel,
    this.bytesDownloaded,
    this.errorMessage,
  });

  @override
  int get hashCode =>
      item.hashCode ^
      status.hashCode ^
      startedAt.hashCode ^
      completedAt.hashCode ^
      savedPath.hashCode ^
      sizeLabel.hashCode ^
      bytesDownloaded.hashCode ^
      errorMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DownloadTask &&
          runtimeType == other.runtimeType &&
          item == other.item &&
          status == other.status &&
          startedAt == other.startedAt &&
          completedAt == other.completedAt &&
          savedPath == other.savedPath &&
          sizeLabel == other.sizeLabel &&
          bytesDownloaded == other.bytesDownloaded &&
          errorMessage == other.errorMessage;
}

/// 下载完成后的结果描述，便于前端提示保存路径与大小。
class DriveDownloadResult {
  final String fileName;
  final String savedPath;
  final BigInt bytesDownloaded;
  final BigInt? expectedSize;

  const DriveDownloadResult({
    required this.fileName,
    required this.savedPath,
    required this.bytesDownloaded,
    this.expectedSize,
  });

  @override
  int get hashCode =>
      fileName.hashCode ^
      savedPath.hashCode ^
      bytesDownloaded.hashCode ^
      expectedSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DriveDownloadResult &&
          runtimeType == other.runtimeType &&
          fileName == other.fileName &&
          savedPath == other.savedPath &&
          bytesDownloaded == other.bytesDownloaded &&
          expectedSize == other.expectedSize;
}

/// OneDrive 概览信息（配额、类型、所有者）。
class DriveInfo {
  final String? id;
  final String? driveType;
  final DriveOwner? owner;
  final DriveQuota? quota;

  const DriveInfo({this.id, this.driveType, this.owner, this.quota});

  @override
  int get hashCode =>
      id.hashCode ^ driveType.hashCode ^ owner.hashCode ^ quota.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DriveInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          driveType == other.driveType &&
          owner == other.owner &&
          quota == other.quota;
}

/// drive item 详情，供属性面板使用。
class DriveItemDetails {
  final String id;
  final String name;
  final BigInt? size;
  final String? mimeType;
  final bool isFolder;
  final PlatformInt64? childCount;
  final String? createdAt;
  final String? lastModifiedAt;
  final String? fileSystemCreatedAt;
  final String? fileSystemModifiedAt;
  final String? webUrl;
  final String? downloadUrl;
  final String? etag;
  final String? ctag;
  final String? parentPath;

  const DriveItemDetails({
    required this.id,
    required this.name,
    this.size,
    this.mimeType,
    required this.isFolder,
    this.childCount,
    this.createdAt,
    this.lastModifiedAt,
    this.fileSystemCreatedAt,
    this.fileSystemModifiedAt,
    this.webUrl,
    this.downloadUrl,
    this.etag,
    this.ctag,
    this.parentPath,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      size.hashCode ^
      mimeType.hashCode ^
      isFolder.hashCode ^
      childCount.hashCode ^
      createdAt.hashCode ^
      lastModifiedAt.hashCode ^
      fileSystemCreatedAt.hashCode ^
      fileSystemModifiedAt.hashCode ^
      webUrl.hashCode ^
      downloadUrl.hashCode ^
      etag.hashCode ^
      ctag.hashCode ^
      parentPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DriveItemDetails &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          size == other.size &&
          mimeType == other.mimeType &&
          isFolder == other.isFolder &&
          childCount == other.childCount &&
          createdAt == other.createdAt &&
          lastModifiedAt == other.lastModifiedAt &&
          fileSystemCreatedAt == other.fileSystemCreatedAt &&
          fileSystemModifiedAt == other.fileSystemModifiedAt &&
          webUrl == other.webUrl &&
          downloadUrl == other.downloadUrl &&
          etag == other.etag &&
          ctag == other.ctag &&
          parentPath == other.parentPath;
}

/// 与 Flutter 侧共享的 OneDrive 文件/文件夹摘要结构。
/// 字段命名保持与 Graph API 对齐，避免额外映射。
class DriveItemSummary {
  final String id;
  final String name;
  final BigInt? size;
  final bool isFolder;
  final PlatformInt64? childCount;
  final String? mimeType;
  final String? lastModified;
  final String? thumbnailUrl;

  const DriveItemSummary({
    required this.id,
    required this.name,
    this.size,
    required this.isFolder,
    this.childCount,
    this.mimeType,
    this.lastModified,
    this.thumbnailUrl,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      size.hashCode ^
      isFolder.hashCode ^
      childCount.hashCode ^
      mimeType.hashCode ^
      lastModified.hashCode ^
      thumbnailUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DriveItemSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          size == other.size &&
          isFolder == other.isFolder &&
          childCount == other.childCount &&
          mimeType == other.mimeType &&
          lastModified == other.lastModified &&
          thumbnailUrl == other.thumbnailUrl;
}

/// OneDrive 所有者基本信息。
class DriveOwner {
  final String? displayName;
  final String? userPrincipalName;
  final String? id;

  const DriveOwner({this.displayName, this.userPrincipalName, this.id});

  @override
  int get hashCode =>
      displayName.hashCode ^ userPrincipalName.hashCode ^ id.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DriveOwner &&
          runtimeType == other.runtimeType &&
          displayName == other.displayName &&
          userPrincipalName == other.userPrincipalName &&
          id == other.id;
}

/// 列表接口的分页结果，包含子项与 nextLink。
class DrivePage {
  final List<DriveItemSummary> items;
  final String? nextLink;

  const DrivePage({required this.items, this.nextLink});

  @override
  int get hashCode => items.hashCode ^ nextLink.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DrivePage &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          nextLink == other.nextLink;
}

/// OneDrive 配额字段，直接保留 Graph 原始值。
class DriveQuota {
  final BigInt? total;
  final BigInt? used;
  final BigInt? remaining;
  final BigInt? deleted;
  final String? state;

  const DriveQuota({
    this.total,
    this.used,
    this.remaining,
    this.deleted,
    this.state,
  });

  @override
  int get hashCode =>
      total.hashCode ^
      used.hashCode ^
      remaining.hashCode ^
      deleted.hashCode ^
      state.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DriveQuota &&
          runtimeType == other.runtimeType &&
          total == other.total &&
          used == other.used &&
          remaining == other.remaining &&
          deleted == other.deleted &&
          state == other.state;
}

/// 分享链接范围（与 Graph 对齐）。
enum LinkScope { anonymous, organization, users }

/// 分享链接类型（与 Graph 对齐）。
enum LinkType { view, edit, embed }

/// 当前账户可用的分享能力（基于 driveType 推断）。
class ShareCapabilities {
  final String? driveType;
  final bool canEmbedLink;
  final bool canOrgScopeLink;
  final bool canPassword;

  const ShareCapabilities({
    this.driveType,
    required this.canEmbedLink,
    required this.canOrgScopeLink,
    required this.canPassword,
  });

  @override
  int get hashCode =>
      driveType.hashCode ^
      canEmbedLink.hashCode ^
      canOrgScopeLink.hashCode ^
      canPassword.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShareCapabilities &&
          runtimeType == other.runtimeType &&
          driveType == other.driveType &&
          canEmbedLink == other.canEmbedLink &&
          canOrgScopeLink == other.canOrgScopeLink &&
          canPassword == other.canPassword;
}

/// 创建分享链接的结果。
class ShareLinkResult {
  final LinkType linkType;
  final LinkScope scope;
  final String? webUrl;
  final String? webHtml;
  final String? permissionId;
  final String? shareId;
  final List<String> roles;
  final bool passwordProtected;

  const ShareLinkResult({
    required this.linkType,
    required this.scope,
    this.webUrl,
    this.webHtml,
    this.permissionId,
    this.shareId,
    required this.roles,
    required this.passwordProtected,
  });

  @override
  int get hashCode =>
      linkType.hashCode ^
      scope.hashCode ^
      webUrl.hashCode ^
      webHtml.hashCode ^
      permissionId.hashCode ^
      shareId.hashCode ^
      roles.hashCode ^
      passwordProtected.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShareLinkResult &&
          runtimeType == other.runtimeType &&
          linkType == other.linkType &&
          scope == other.scope &&
          webUrl == other.webUrl &&
          webHtml == other.webHtml &&
          permissionId == other.permissionId &&
          shareId == other.shareId &&
          roles == other.roles &&
          passwordProtected == other.passwordProtected;
}

/// 上传进度事件，用于前端展示实时上传状态。
class UploadProgressUpdate {
  final String taskId;
  final BigInt bytesUploaded;
  final BigInt? expectedSize;
  final double? speedBps;
  final PlatformInt64 timestampMillis;

  const UploadProgressUpdate({
    required this.taskId,
    required this.bytesUploaded,
    this.expectedSize,
    this.speedBps,
    required this.timestampMillis,
  });

  @override
  int get hashCode =>
      taskId.hashCode ^
      bytesUploaded.hashCode ^
      expectedSize.hashCode ^
      speedBps.hashCode ^
      timestampMillis.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UploadProgressUpdate &&
          runtimeType == other.runtimeType &&
          taskId == other.taskId &&
          bytesUploaded == other.bytesUploaded &&
          expectedSize == other.expectedSize &&
          speedBps == other.speedBps &&
          timestampMillis == other.timestampMillis;
}

/// 上传队列状态。
class UploadQueueState {
  final List<UploadTask> active;
  final List<UploadTask> completed;
  final List<UploadTask> failed;

  const UploadQueueState({
    required this.active,
    required this.completed,
    required this.failed,
  });

  static Future<UploadQueueState> default_() =>
      RustLib.instance.api.crateApiDriveModelsUploadQueueStateDefault();

  @override
  int get hashCode => active.hashCode ^ completed.hashCode ^ failed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UploadQueueState &&
          runtimeType == other.runtimeType &&
          active == other.active &&
          completed == other.completed &&
          failed == other.failed;
}

/// 上传任务状态。
enum UploadStatus { inProgress, completed, failed, cancelled }

/// 单条上传任务详情。
class UploadTask {
  final String taskId;
  final String fileName;
  final String localPath;
  final BigInt? size;
  final String? mimeType;
  final String? parentId;
  final String? remoteId;
  final UploadStatus status;
  final PlatformInt64 startedAt;
  final PlatformInt64? completedAt;
  final BigInt? bytesUploaded;
  final String? errorMessage;
  final String? sessionUrl;

  const UploadTask({
    required this.taskId,
    required this.fileName,
    required this.localPath,
    this.size,
    this.mimeType,
    this.parentId,
    this.remoteId,
    required this.status,
    required this.startedAt,
    this.completedAt,
    this.bytesUploaded,
    this.errorMessage,
    this.sessionUrl,
  });

  @override
  int get hashCode =>
      taskId.hashCode ^
      fileName.hashCode ^
      localPath.hashCode ^
      size.hashCode ^
      mimeType.hashCode ^
      parentId.hashCode ^
      remoteId.hashCode ^
      status.hashCode ^
      startedAt.hashCode ^
      completedAt.hashCode ^
      bytesUploaded.hashCode ^
      errorMessage.hashCode ^
      sessionUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UploadTask &&
          runtimeType == other.runtimeType &&
          taskId == other.taskId &&
          fileName == other.fileName &&
          localPath == other.localPath &&
          size == other.size &&
          mimeType == other.mimeType &&
          parentId == other.parentId &&
          remoteId == other.remoteId &&
          status == other.status &&
          startedAt == other.startedAt &&
          completedAt == other.completedAt &&
          bytesUploaded == other.bytesUploaded &&
          errorMessage == other.errorMessage &&
          sessionUrl == other.sessionUrl;
}
