// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// 下载队列状态，包含进行中、已完成与失败任务列表。
class DownloadQueueState {
  final List<DownloadTask> active;
  final List<DownloadTask> completed;
  final List<DownloadTask> failed;

  const DownloadQueueState({
    required this.active,
    required this.completed,
    required this.failed,
  });

  static Future<DownloadQueueState> default_() =>
      RustLib.instance.api.crateApiDriveModelsDownloadQueueStateDefault();

  @override
  int get hashCode => active.hashCode ^ completed.hashCode ^ failed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DownloadQueueState &&
          runtimeType == other.runtimeType &&
          active == other.active &&
          completed == other.completed &&
          failed == other.failed;
}

/// 下载任务状态，迁移至 Rust 端统一管理。
enum DownloadStatus { inProgress, completed, failed }

/// 单条下载任务详情，供 Flutter 展示进度与历史。
class DownloadTask {
  final DriveItemSummary item;
  final DownloadStatus status;
  final PlatformInt64 startedAt;
  final PlatformInt64? completedAt;
  final String? savedPath;
  final BigInt? sizeLabel;
  final BigInt? bytesDownloaded;
  final String? errorMessage;

  const DownloadTask({
    required this.item,
    required this.status,
    required this.startedAt,
    this.completedAt,
    this.savedPath,
    this.sizeLabel,
    this.bytesDownloaded,
    this.errorMessage,
  });

  @override
  int get hashCode =>
      item.hashCode ^
      status.hashCode ^
      startedAt.hashCode ^
      completedAt.hashCode ^
      savedPath.hashCode ^
      sizeLabel.hashCode ^
      bytesDownloaded.hashCode ^
      errorMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DownloadTask &&
          runtimeType == other.runtimeType &&
          item == other.item &&
          status == other.status &&
          startedAt == other.startedAt &&
          completedAt == other.completedAt &&
          savedPath == other.savedPath &&
          sizeLabel == other.sizeLabel &&
          bytesDownloaded == other.bytesDownloaded &&
          errorMessage == other.errorMessage;
}

/// 下载完成后的结果描述，便于前端提示保存路径与大小。
class DriveDownloadResult {
  final String fileName;
  final String savedPath;
  final BigInt bytesDownloaded;
  final BigInt? expectedSize;

  const DriveDownloadResult({
    required this.fileName,
    required this.savedPath,
    required this.bytesDownloaded,
    this.expectedSize,
  });

  @override
  int get hashCode =>
      fileName.hashCode ^
      savedPath.hashCode ^
      bytesDownloaded.hashCode ^
      expectedSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DriveDownloadResult &&
          runtimeType == other.runtimeType &&
          fileName == other.fileName &&
          savedPath == other.savedPath &&
          bytesDownloaded == other.bytesDownloaded &&
          expectedSize == other.expectedSize;
}

/// 与 Flutter 侧共享的 OneDrive 文件/文件夹摘要结构。
/// 字段命名保持与 Graph API 对齐，避免额外映射。
class DriveItemSummary {
  final String id;
  final String name;
  final BigInt? size;
  final bool isFolder;
  final PlatformInt64? childCount;
  final String? mimeType;
  final String? lastModified;
  final String? thumbnailUrl;

  const DriveItemSummary({
    required this.id,
    required this.name,
    this.size,
    required this.isFolder,
    this.childCount,
    this.mimeType,
    this.lastModified,
    this.thumbnailUrl,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      size.hashCode ^
      isFolder.hashCode ^
      childCount.hashCode ^
      mimeType.hashCode ^
      lastModified.hashCode ^
      thumbnailUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DriveItemSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          size == other.size &&
          isFolder == other.isFolder &&
          childCount == other.childCount &&
          mimeType == other.mimeType &&
          lastModified == other.lastModified &&
          thumbnailUrl == other.thumbnailUrl;
}

/// 列表接口的分页结果，包含子项与 nextLink。
class DrivePage {
  final List<DriveItemSummary> items;
  final String? nextLink;

  const DrivePage({required this.items, this.nextLink});

  @override
  int get hashCode => items.hashCode ^ nextLink.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DrivePage &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          nextLink == other.nextLink;
}
