// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_delta_items`, `apply_delta_sync`, `build_initial_delta_url`, `delta_item_to_record`, `fetch_delta_page`, `finalize_folder_deletes`, `handle_deleted_item`, `is_delta_reset`, `map_to_summary`, `normalize_page_size`, `parse_offset`, `run_full_delta_sync`, `sync_error_message`, `sync_offline_index`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DeletedFacet`, `DeltaItemDto`, `DeltaPage`, `GraphErrorEnvelope`, `GraphErrorPayload`, `SyncError`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

Future<OfflineIndexStatus> rebuildOfflineIndex() =>
    RustLib.instance.api.crateApiDriveOfflineIndexRebuildOfflineIndex();

Future<OfflineIndexStatus> getOfflineIndexStatus() =>
    RustLib.instance.api.crateApiDriveOfflineIndexGetOfflineIndexStatus();

Future<DrivePage> searchOfflineIndex({
  required String query,
  String? folderId,
  String? nextLink,
  int? top,
}) => RustLib.instance.api.crateApiDriveOfflineIndexSearchOfflineIndex(
  query: query,
  folderId: folderId,
  nextLink: nextLink,
  top: top,
);
