// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `collect_records`, `map_to_summary`, `normalize_page_size`, `parse_offset`, `to_record`

Future<OfflineIndexStatus> rebuildOfflineIndex() =>
    RustLib.instance.api.crateApiDriveOfflineIndexRebuildOfflineIndex();

Future<OfflineIndexStatus> getOfflineIndexStatus() =>
    RustLib.instance.api.crateApiDriveOfflineIndexGetOfflineIndexStatus();

Future<DrivePage> searchOfflineIndex({
  required String query,
  String? folderId,
  String? nextLink,
  int? top,
}) => RustLib.instance.api.crateApiDriveOfflineIndexSearchOfflineIndex(
  query: query,
  folderId: folderId,
  nextLink: nextLink,
  top: top,
);
