// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_search_url`

/// 在 OneDrive 中执行远程搜索。
/// - `folder_id` 为空时，从 root 作为搜索范围。
/// - `next_link` 优先级最高，用于分页续取。
Future<DrivePage> searchDriveItems({
  required String query,
  String? folderId,
  String? nextLink,
  int? top,
}) => RustLib.instance.api.crateApiDriveSearchSearchDriveItems(
  query: query,
  folderId: folderId,
  nextLink: nextLink,
  top: top,
);
