// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `as_graph_str`, `as_graph_str`, `from_drive_type`, `from_graph_str`, `from_graph_str`, `new`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CreateLinkRequest`, `LinkDto`, `PermissionDto`, `RecipientDto`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`, `fmt`, `fmt`, `try_from`

/// 读取当前账户的分享能力，便于前端灰掉不支持的选项。
Future<ShareCapabilities> getShareCapabilities() =>
    RustLib.instance.api.crateApiDriveShareGetShareCapabilities();

/// 为指定 item 创建分享链接（支持个人/企业差异）。
Future<ShareLinkResult> createShareLink({
  required String itemId,
  required LinkType linkType,
  required LinkScope scope,
  String? password,
  String? expirationDateTime,
  bool? retainInheritedPermissions,
  List<String>? recipients,
}) => RustLib.instance.api.crateApiDriveShareCreateShareLink(
  itemId: itemId,
  linkType: linkType,
  scope: scope,
  password: password,
  expirationDateTime: expirationDateTime,
  retainInheritedPermissions: retainInheritedPermissions,
  recipients: recipients,
);
