// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<UploadQueueState> uploadQueueState() =>
    RustLib.instance.api.crateApiDriveUploadManagerUploadQueueState();

Future<UploadQueueState> enqueueUploadTask({
  String? parentId,
  required String fileName,
  required String localPath,
  required List<int> content,
  required bool overwrite,
}) => RustLib.instance.api.crateApiDriveUploadManagerEnqueueUploadTask(
  parentId: parentId,
  fileName: fileName,
  localPath: localPath,
  content: content,
  overwrite: overwrite,
);

Future<UploadQueueState> enqueueLargeUploadTask({
  String? parentId,
  required String fileName,
  required String localPath,
  required bool overwrite,
}) => RustLib.instance.api.crateApiDriveUploadManagerEnqueueLargeUploadTask(
  parentId: parentId,
  fileName: fileName,
  localPath: localPath,
  overwrite: overwrite,
);

Future<UploadQueueState> removeUploadTask({required String taskId}) => RustLib
    .instance
    .api
    .crateApiDriveUploadManagerRemoveUploadTask(taskId: taskId);

Future<UploadQueueState> cancelUploadTask({required String taskId}) => RustLib
    .instance
    .api
    .crateApiDriveUploadManagerCancelUploadTask(taskId: taskId);

Future<UploadQueueState> clearFailedUploadTasks() =>
    RustLib.instance.api.crateApiDriveUploadManagerClearFailedUploadTasks();

Future<UploadQueueState> clearUploadHistory() =>
    RustLib.instance.api.crateApiDriveUploadManagerClearUploadHistory();

Stream<UploadProgressUpdate> uploadProgressStream() =>
    RustLib.instance.api.crateApiDriveUploadManagerUploadProgressStream();
