// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `align_chunk_size`, `cancel_upload_session`, `create_upload_session`, `get_upload_session_status`, `new`, `parse_next_start`, `upload_chunk_with_retry`, `upload_large_file_with_hooks`, `upload_small_file_with_hooks`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DriveItemUploadResponse`, `ProgressReader`, `UploadChunkError`, `UploadChunkResult`, `UploadFileFacet`, `UploadSessionResponse`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`, `fmt`, `from`, `read`

/// 上传小文件（推荐 10MB 内，硬上限 250MB），存放到指定文件夹。
/// - 当 overwrite=true 时，如果存在同名文件，将直接覆盖。
/// - 当 overwrite=false 时，使用 Graph 的 rename 行为避免冲突。
/// - parent_id 为空时默认上传到根目录。
Future<DriveItemSummary> uploadSmallFile({
  String? parentId,
  required String fileName,
  required List<int> content,
  required bool overwrite,
}) => RustLib.instance.api.crateApiDriveUploadUploadSmallFile(
  parentId: parentId,
  fileName: fileName,
  content: content,
  overwrite: overwrite,
);
