// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/auth/auth.dart';
import 'api/auth/refresh.dart';
import 'api/drive/delete.dart';
import 'api/drive/download.dart';
import 'api/drive/download_manager.dart';
import 'api/drive/info.dart';
import 'api/drive/list.dart';
import 'api/drive/models.dart';
import 'api/drive/upload.dart';
import 'api/drive/upload_manager.dart';
import 'api/settings/download_concurrency.dart';
import 'api/settings/download_directory.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -1472070265;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_skydrivex',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<AuthTokens> crateApiAuthAuthAuthenticateViaBrowser({
    required String clientId,
    required List<String> scopes,
  });

  Future<DownloadQueueState> crateApiDriveDownloadManagerCancelDownloadTask({
    required String itemId,
  });

  Future<UploadQueueState> crateApiDriveUploadManagerCancelUploadTask({
    required String taskId,
  });

  Future<DownloadQueueState> crateApiDriveDownloadManagerClearDownloadHistory();

  Future<DownloadQueueState>
  crateApiDriveDownloadManagerClearFailedDownloadTasks();

  Future<UploadQueueState> crateApiDriveUploadManagerClearFailedUploadTasks();

  Future<void> crateApiAuthAuthClearPersistedAuthState();

  Future<UploadQueueState> crateApiDriveUploadManagerClearUploadHistory();

  Future<void> crateApiDriveDeleteDeleteDriveItem({
    required String itemId,
    String? ifMatch,
    required bool bypassLocks,
  });

  Future<DriveDownloadResult> crateApiDriveDownloadDownloadDriveItem({
    required String itemId,
    required String targetDir,
    required bool overwrite,
  });

  Stream<DownloadProgressUpdate>
  crateApiDriveDownloadManagerDownloadProgressStream();

  Future<DownloadQueueState> crateApiDriveDownloadManagerDownloadQueueState();

  Future<DownloadQueueState> crateApiDriveModelsDownloadQueueStateDefault();

  Future<DownloadQueueState> crateApiDriveDownloadManagerEnqueueDownloadTask({
    required DriveItemSummary item,
    required String targetDir,
    required bool overwrite,
  });

  Future<UploadQueueState> crateApiDriveUploadManagerEnqueueLargeUploadTask({
    String? parentId,
    required String fileName,
    required String localPath,
    required bool overwrite,
  });

  Future<UploadQueueState> crateApiDriveUploadManagerEnqueueUploadTask({
    String? parentId,
    required String fileName,
    required String localPath,
    required List<int> content,
    required bool overwrite,
  });

  Future<int> crateApiSettingsDownloadConcurrencyGetDownloadConcurrency();

  Future<String> crateApiSettingsDownloadDirectoryGetDownloadDirectory();

  Future<DriveInfo> crateApiDriveInfoGetDriveOverview();

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  Future<DrivePage> crateApiDriveListListDriveChildren({
    String? folderId,
    String? folderPath,
    String? nextLink,
  });

  Future<StoredAuthState?> crateApiAuthAuthLoadPersistedAuthState();

  Future<void> crateApiAuthAuthPersistAuthState({
    required String clientId,
    required AuthTokens tokens,
  });

  Future<StoredAuthState> crateApiAuthRefreshRefreshTokens();

  Future<DownloadQueueState> crateApiDriveDownloadManagerRemoveDownloadTask({
    required String itemId,
  });

  Future<UploadQueueState> crateApiDriveUploadManagerRemoveUploadTask({
    required String taskId,
  });

  Future<int> crateApiSettingsDownloadConcurrencySetDownloadConcurrency({
    required int limit,
  });

  Future<String> crateApiSettingsDownloadDirectorySetDownloadDirectory({
    required String path,
  });

  Stream<UploadProgressUpdate> crateApiDriveUploadManagerUploadProgressStream();

  Future<UploadQueueState> crateApiDriveUploadManagerUploadQueueState();

  Future<UploadQueueState> crateApiDriveModelsUploadQueueStateDefault();

  Future<DriveItemSummary> crateApiDriveUploadUploadSmallFile({
    String? parentId,
    required String fileName,
    required List<int> content,
    required bool overwrite,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<AuthTokens> crateApiAuthAuthAuthenticateViaBrowser({
    required String clientId,
    required List<String> scopes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(clientId, serializer);
          sse_encode_list_String(scopes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_auth_tokens,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAuthAuthAuthenticateViaBrowserConstMeta,
        argValues: [clientId, scopes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthAuthAuthenticateViaBrowserConstMeta =>
      const TaskConstMeta(
        debugName: "authenticate_via_browser",
        argNames: ["clientId", "scopes"],
      );

  @override
  Future<DownloadQueueState> crateApiDriveDownloadManagerCancelDownloadTask({
    required String itemId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(itemId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_download_queue_state,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDriveDownloadManagerCancelDownloadTaskConstMeta,
        argValues: [itemId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDriveDownloadManagerCancelDownloadTaskConstMeta =>
      const TaskConstMeta(
        debugName: "cancel_download_task",
        argNames: ["itemId"],
      );

  @override
  Future<UploadQueueState> crateApiDriveUploadManagerCancelUploadTask({
    required String taskId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(taskId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_upload_queue_state,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDriveUploadManagerCancelUploadTaskConstMeta,
        argValues: [taskId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDriveUploadManagerCancelUploadTaskConstMeta =>
      const TaskConstMeta(
        debugName: "cancel_upload_task",
        argNames: ["taskId"],
      );

  @override
  Future<DownloadQueueState>
  crateApiDriveDownloadManagerClearDownloadHistory() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_download_queue_state,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDriveDownloadManagerClearDownloadHistoryConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiDriveDownloadManagerClearDownloadHistoryConstMeta =>
      const TaskConstMeta(debugName: "clear_download_history", argNames: []);

  @override
  Future<DownloadQueueState>
  crateApiDriveDownloadManagerClearFailedDownloadTasks() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_download_queue_state,
          decodeErrorData: sse_decode_String,
        ),
        constMeta:
            kCrateApiDriveDownloadManagerClearFailedDownloadTasksConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiDriveDownloadManagerClearFailedDownloadTasksConstMeta =>
      const TaskConstMeta(
        debugName: "clear_failed_download_tasks",
        argNames: [],
      );

  @override
  Future<UploadQueueState> crateApiDriveUploadManagerClearFailedUploadTasks() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_upload_queue_state,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDriveUploadManagerClearFailedUploadTasksConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiDriveUploadManagerClearFailedUploadTasksConstMeta =>
      const TaskConstMeta(debugName: "clear_failed_upload_tasks", argNames: []);

  @override
  Future<void> crateApiAuthAuthClearPersistedAuthState() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAuthAuthClearPersistedAuthStateConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthAuthClearPersistedAuthStateConstMeta =>
      const TaskConstMeta(
        debugName: "clear_persisted_auth_state",
        argNames: [],
      );

  @override
  Future<UploadQueueState> crateApiDriveUploadManagerClearUploadHistory() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_upload_queue_state,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDriveUploadManagerClearUploadHistoryConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDriveUploadManagerClearUploadHistoryConstMeta =>
      const TaskConstMeta(debugName: "clear_upload_history", argNames: []);

  @override
  Future<void> crateApiDriveDeleteDeleteDriveItem({
    required String itemId,
    String? ifMatch,
    required bool bypassLocks,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(itemId, serializer);
          sse_encode_opt_String(ifMatch, serializer);
          sse_encode_bool(bypassLocks, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDriveDeleteDeleteDriveItemConstMeta,
        argValues: [itemId, ifMatch, bypassLocks],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDriveDeleteDeleteDriveItemConstMeta =>
      const TaskConstMeta(
        debugName: "delete_drive_item",
        argNames: ["itemId", "ifMatch", "bypassLocks"],
      );

  @override
  Future<DriveDownloadResult> crateApiDriveDownloadDownloadDriveItem({
    required String itemId,
    required String targetDir,
    required bool overwrite,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(itemId, serializer);
          sse_encode_String(targetDir, serializer);
          sse_encode_bool(overwrite, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_drive_download_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDriveDownloadDownloadDriveItemConstMeta,
        argValues: [itemId, targetDir, overwrite],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDriveDownloadDownloadDriveItemConstMeta =>
      const TaskConstMeta(
        debugName: "download_drive_item",
        argNames: ["itemId", "targetDir", "overwrite"],
      );

  @override
  Stream<DownloadProgressUpdate>
  crateApiDriveDownloadManagerDownloadProgressStream() {
    final streamSink = RustStreamSink<DownloadProgressUpdate>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_download_progress_update_Sse(
              streamSink,
              serializer,
            );
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 11,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta:
              kCrateApiDriveDownloadManagerDownloadProgressStreamConstMeta,
          argValues: [streamSink],
          apiImpl: this,
        ),
      ),
    );
    return streamSink.stream;
  }

  TaskConstMeta
  get kCrateApiDriveDownloadManagerDownloadProgressStreamConstMeta =>
      const TaskConstMeta(
        debugName: "download_progress_stream",
        argNames: ["streamSink"],
      );

  @override
  Future<DownloadQueueState> crateApiDriveDownloadManagerDownloadQueueState() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_download_queue_state,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDriveDownloadManagerDownloadQueueStateConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDriveDownloadManagerDownloadQueueStateConstMeta =>
      const TaskConstMeta(debugName: "download_queue_state", argNames: []);

  @override
  Future<DownloadQueueState> crateApiDriveModelsDownloadQueueStateDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_download_queue_state,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDriveModelsDownloadQueueStateDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDriveModelsDownloadQueueStateDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "download_queue_state_default",
        argNames: [],
      );

  @override
  Future<DownloadQueueState> crateApiDriveDownloadManagerEnqueueDownloadTask({
    required DriveItemSummary item,
    required String targetDir,
    required bool overwrite,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_drive_item_summary(item, serializer);
          sse_encode_String(targetDir, serializer);
          sse_encode_bool(overwrite, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_download_queue_state,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDriveDownloadManagerEnqueueDownloadTaskConstMeta,
        argValues: [item, targetDir, overwrite],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDriveDownloadManagerEnqueueDownloadTaskConstMeta =>
      const TaskConstMeta(
        debugName: "enqueue_download_task",
        argNames: ["item", "targetDir", "overwrite"],
      );

  @override
  Future<UploadQueueState> crateApiDriveUploadManagerEnqueueLargeUploadTask({
    String? parentId,
    required String fileName,
    required String localPath,
    required bool overwrite,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(parentId, serializer);
          sse_encode_String(fileName, serializer);
          sse_encode_String(localPath, serializer);
          sse_encode_bool(overwrite, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_upload_queue_state,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDriveUploadManagerEnqueueLargeUploadTaskConstMeta,
        argValues: [parentId, fileName, localPath, overwrite],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiDriveUploadManagerEnqueueLargeUploadTaskConstMeta =>
      const TaskConstMeta(
        debugName: "enqueue_large_upload_task",
        argNames: ["parentId", "fileName", "localPath", "overwrite"],
      );

  @override
  Future<UploadQueueState> crateApiDriveUploadManagerEnqueueUploadTask({
    String? parentId,
    required String fileName,
    required String localPath,
    required List<int> content,
    required bool overwrite,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(parentId, serializer);
          sse_encode_String(fileName, serializer);
          sse_encode_String(localPath, serializer);
          sse_encode_list_prim_u_8_loose(content, serializer);
          sse_encode_bool(overwrite, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_upload_queue_state,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDriveUploadManagerEnqueueUploadTaskConstMeta,
        argValues: [parentId, fileName, localPath, content, overwrite],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDriveUploadManagerEnqueueUploadTaskConstMeta =>
      const TaskConstMeta(
        debugName: "enqueue_upload_task",
        argNames: ["parentId", "fileName", "localPath", "content", "overwrite"],
      );

  @override
  Future<int> crateApiSettingsDownloadConcurrencyGetDownloadConcurrency() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_String,
        ),
        constMeta:
            kCrateApiSettingsDownloadConcurrencyGetDownloadConcurrencyConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiSettingsDownloadConcurrencyGetDownloadConcurrencyConstMeta =>
      const TaskConstMeta(debugName: "get_download_concurrency", argNames: []);

  @override
  Future<String> crateApiSettingsDownloadDirectoryGetDownloadDirectory() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta:
            kCrateApiSettingsDownloadDirectoryGetDownloadDirectoryConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiSettingsDownloadDirectoryGetDownloadDirectoryConstMeta =>
      const TaskConstMeta(debugName: "get_download_directory", argNames: []);

  @override
  Future<DriveInfo> crateApiDriveInfoGetDriveOverview() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_drive_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDriveInfoGetDriveOverviewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDriveInfoGetDriveOverviewConstMeta =>
      const TaskConstMeta(debugName: "get_drive_overview", argNames: []);

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<DrivePage> crateApiDriveListListDriveChildren({
    String? folderId,
    String? folderPath,
    String? nextLink,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(folderId, serializer);
          sse_encode_opt_String(folderPath, serializer);
          sse_encode_opt_String(nextLink, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_drive_page,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDriveListListDriveChildrenConstMeta,
        argValues: [folderId, folderPath, nextLink],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDriveListListDriveChildrenConstMeta =>
      const TaskConstMeta(
        debugName: "list_drive_children",
        argNames: ["folderId", "folderPath", "nextLink"],
      );

  @override
  Future<StoredAuthState?> crateApiAuthAuthLoadPersistedAuthState() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_stored_auth_state,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAuthAuthLoadPersistedAuthStateConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthAuthLoadPersistedAuthStateConstMeta =>
      const TaskConstMeta(debugName: "load_persisted_auth_state", argNames: []);

  @override
  Future<void> crateApiAuthAuthPersistAuthState({
    required String clientId,
    required AuthTokens tokens,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(clientId, serializer);
          sse_encode_box_autoadd_auth_tokens(tokens, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAuthAuthPersistAuthStateConstMeta,
        argValues: [clientId, tokens],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthAuthPersistAuthStateConstMeta =>
      const TaskConstMeta(
        debugName: "persist_auth_state",
        argNames: ["clientId", "tokens"],
      );

  @override
  Future<StoredAuthState> crateApiAuthRefreshRefreshTokens() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_stored_auth_state,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAuthRefreshRefreshTokensConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthRefreshRefreshTokensConstMeta =>
      const TaskConstMeta(debugName: "refresh_tokens", argNames: []);

  @override
  Future<DownloadQueueState> crateApiDriveDownloadManagerRemoveDownloadTask({
    required String itemId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(itemId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_download_queue_state,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDriveDownloadManagerRemoveDownloadTaskConstMeta,
        argValues: [itemId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDriveDownloadManagerRemoveDownloadTaskConstMeta =>
      const TaskConstMeta(
        debugName: "remove_download_task",
        argNames: ["itemId"],
      );

  @override
  Future<UploadQueueState> crateApiDriveUploadManagerRemoveUploadTask({
    required String taskId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(taskId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_upload_queue_state,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDriveUploadManagerRemoveUploadTaskConstMeta,
        argValues: [taskId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDriveUploadManagerRemoveUploadTaskConstMeta =>
      const TaskConstMeta(
        debugName: "remove_upload_task",
        argNames: ["taskId"],
      );

  @override
  Future<int> crateApiSettingsDownloadConcurrencySetDownloadConcurrency({
    required int limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_String,
        ),
        constMeta:
            kCrateApiSettingsDownloadConcurrencySetDownloadConcurrencyConstMeta,
        argValues: [limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiSettingsDownloadConcurrencySetDownloadConcurrencyConstMeta =>
      const TaskConstMeta(
        debugName: "set_download_concurrency",
        argNames: ["limit"],
      );

  @override
  Future<String> crateApiSettingsDownloadDirectorySetDownloadDirectory({
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta:
            kCrateApiSettingsDownloadDirectorySetDownloadDirectoryConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiSettingsDownloadDirectorySetDownloadDirectoryConstMeta =>
      const TaskConstMeta(
        debugName: "set_download_directory",
        argNames: ["path"],
      );

  @override
  Stream<UploadProgressUpdate>
  crateApiDriveUploadManagerUploadProgressStream() {
    final streamSink = RustStreamSink<UploadProgressUpdate>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_upload_progress_update_Sse(
              streamSink,
              serializer,
            );
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 30,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiDriveUploadManagerUploadProgressStreamConstMeta,
          argValues: [streamSink],
          apiImpl: this,
        ),
      ),
    );
    return streamSink.stream;
  }

  TaskConstMeta get kCrateApiDriveUploadManagerUploadProgressStreamConstMeta =>
      const TaskConstMeta(
        debugName: "upload_progress_stream",
        argNames: ["streamSink"],
      );

  @override
  Future<UploadQueueState> crateApiDriveUploadManagerUploadQueueState() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_upload_queue_state,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDriveUploadManagerUploadQueueStateConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDriveUploadManagerUploadQueueStateConstMeta =>
      const TaskConstMeta(debugName: "upload_queue_state", argNames: []);

  @override
  Future<UploadQueueState> crateApiDriveModelsUploadQueueStateDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 32,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_upload_queue_state,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDriveModelsUploadQueueStateDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDriveModelsUploadQueueStateDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "upload_queue_state_default",
        argNames: [],
      );

  @override
  Future<DriveItemSummary> crateApiDriveUploadUploadSmallFile({
    String? parentId,
    required String fileName,
    required List<int> content,
    required bool overwrite,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(parentId, serializer);
          sse_encode_String(fileName, serializer);
          sse_encode_list_prim_u_8_loose(content, serializer);
          sse_encode_bool(overwrite, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 33,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_drive_item_summary,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDriveUploadUploadSmallFileConstMeta,
        argValues: [parentId, fileName, content, overwrite],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDriveUploadUploadSmallFileConstMeta =>
      const TaskConstMeta(
        debugName: "upload_small_file",
        argNames: ["parentId", "fileName", "content", "overwrite"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<DownloadProgressUpdate>
  dco_decode_StreamSink_download_progress_update_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<UploadProgressUpdate>
  dco_decode_StreamSink_upload_progress_update_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AuthTokens dco_decode_auth_tokens(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return AuthTokens(
      accessToken: dco_decode_String(arr[0]),
      refreshToken: dco_decode_opt_String(arr[1]),
      expiresIn: dco_decode_opt_box_autoadd_u_64(arr[2]),
      idToken: dco_decode_opt_String(arr[3]),
      scope: dco_decode_opt_String(arr[4]),
      tokenType: dco_decode_opt_String(arr[5]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  AuthTokens dco_decode_box_autoadd_auth_tokens(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_auth_tokens(raw);
  }

  @protected
  DriveItemSummary dco_decode_box_autoadd_drive_item_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_drive_item_summary(raw);
  }

  @protected
  DriveOwner dco_decode_box_autoadd_drive_owner(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_drive_owner(raw);
  }

  @protected
  DriveQuota dco_decode_box_autoadd_drive_quota(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_drive_quota(raw);
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  StoredAuthState dco_decode_box_autoadd_stored_auth_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_stored_auth_state(raw);
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  DownloadProgressUpdate dco_decode_download_progress_update(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return DownloadProgressUpdate(
      itemId: dco_decode_String(arr[0]),
      bytesDownloaded: dco_decode_u_64(arr[1]),
      expectedSize: dco_decode_opt_box_autoadd_u_64(arr[2]),
      speedBps: dco_decode_opt_box_autoadd_f_64(arr[3]),
      timestampMillis: dco_decode_i_64(arr[4]),
    );
  }

  @protected
  DownloadQueueState dco_decode_download_queue_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return DownloadQueueState(
      active: dco_decode_list_download_task(arr[0]),
      completed: dco_decode_list_download_task(arr[1]),
      failed: dco_decode_list_download_task(arr[2]),
    );
  }

  @protected
  DownloadStatus dco_decode_download_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return DownloadStatus.values[raw as int];
  }

  @protected
  DownloadTask dco_decode_download_task(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return DownloadTask(
      item: dco_decode_drive_item_summary(arr[0]),
      status: dco_decode_download_status(arr[1]),
      startedAt: dco_decode_i_64(arr[2]),
      completedAt: dco_decode_opt_box_autoadd_i_64(arr[3]),
      savedPath: dco_decode_opt_String(arr[4]),
      sizeLabel: dco_decode_opt_box_autoadd_u_64(arr[5]),
      bytesDownloaded: dco_decode_opt_box_autoadd_u_64(arr[6]),
      errorMessage: dco_decode_opt_String(arr[7]),
    );
  }

  @protected
  DriveDownloadResult dco_decode_drive_download_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return DriveDownloadResult(
      fileName: dco_decode_String(arr[0]),
      savedPath: dco_decode_String(arr[1]),
      bytesDownloaded: dco_decode_u_64(arr[2]),
      expectedSize: dco_decode_opt_box_autoadd_u_64(arr[3]),
    );
  }

  @protected
  DriveInfo dco_decode_drive_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return DriveInfo(
      id: dco_decode_opt_String(arr[0]),
      driveType: dco_decode_opt_String(arr[1]),
      owner: dco_decode_opt_box_autoadd_drive_owner(arr[2]),
      quota: dco_decode_opt_box_autoadd_drive_quota(arr[3]),
    );
  }

  @protected
  DriveItemSummary dco_decode_drive_item_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return DriveItemSummary(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      size: dco_decode_opt_box_autoadd_u_64(arr[2]),
      isFolder: dco_decode_bool(arr[3]),
      childCount: dco_decode_opt_box_autoadd_i_64(arr[4]),
      mimeType: dco_decode_opt_String(arr[5]),
      lastModified: dco_decode_opt_String(arr[6]),
      thumbnailUrl: dco_decode_opt_String(arr[7]),
    );
  }

  @protected
  DriveOwner dco_decode_drive_owner(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return DriveOwner(
      displayName: dco_decode_opt_String(arr[0]),
      userPrincipalName: dco_decode_opt_String(arr[1]),
      id: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  DrivePage dco_decode_drive_page(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return DrivePage(
      items: dco_decode_list_drive_item_summary(arr[0]),
      nextLink: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  DriveQuota dco_decode_drive_quota(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return DriveQuota(
      total: dco_decode_opt_box_autoadd_u_64(arr[0]),
      used: dco_decode_opt_box_autoadd_u_64(arr[1]),
      remaining: dco_decode_opt_box_autoadd_u_64(arr[2]),
      deleted: dco_decode_opt_box_autoadd_u_64(arr[3]),
      state: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<DownloadTask> dco_decode_list_download_task(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_download_task).toList();
  }

  @protected
  List<DriveItemSummary> dco_decode_list_drive_item_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_drive_item_summary).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<UploadTask> dco_decode_list_upload_task(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_upload_task).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  DriveOwner? dco_decode_opt_box_autoadd_drive_owner(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_drive_owner(raw);
  }

  @protected
  DriveQuota? dco_decode_opt_box_autoadd_drive_quota(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_drive_quota(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  StoredAuthState? dco_decode_opt_box_autoadd_stored_auth_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_stored_auth_state(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  StoredAuthState dco_decode_stored_auth_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return StoredAuthState(
      clientId: dco_decode_String(arr[0]),
      tokens: dco_decode_auth_tokens(arr[1]),
      updatedAtMillis: dco_decode_i_64(arr[2]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  UploadProgressUpdate dco_decode_upload_progress_update(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return UploadProgressUpdate(
      taskId: dco_decode_String(arr[0]),
      bytesUploaded: dco_decode_u_64(arr[1]),
      expectedSize: dco_decode_opt_box_autoadd_u_64(arr[2]),
      speedBps: dco_decode_opt_box_autoadd_f_64(arr[3]),
      timestampMillis: dco_decode_i_64(arr[4]),
    );
  }

  @protected
  UploadQueueState dco_decode_upload_queue_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return UploadQueueState(
      active: dco_decode_list_upload_task(arr[0]),
      completed: dco_decode_list_upload_task(arr[1]),
      failed: dco_decode_list_upload_task(arr[2]),
    );
  }

  @protected
  UploadStatus dco_decode_upload_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return UploadStatus.values[raw as int];
  }

  @protected
  UploadTask dco_decode_upload_task(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 13)
      throw Exception('unexpected arr length: expect 13 but see ${arr.length}');
    return UploadTask(
      taskId: dco_decode_String(arr[0]),
      fileName: dco_decode_String(arr[1]),
      localPath: dco_decode_String(arr[2]),
      size: dco_decode_opt_box_autoadd_u_64(arr[3]),
      mimeType: dco_decode_opt_String(arr[4]),
      parentId: dco_decode_opt_String(arr[5]),
      remoteId: dco_decode_opt_String(arr[6]),
      status: dco_decode_upload_status(arr[7]),
      startedAt: dco_decode_i_64(arr[8]),
      completedAt: dco_decode_opt_box_autoadd_i_64(arr[9]),
      bytesUploaded: dco_decode_opt_box_autoadd_u_64(arr[10]),
      errorMessage: dco_decode_opt_String(arr[11]),
      sessionUrl: dco_decode_opt_String(arr[12]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<DownloadProgressUpdate>
  sse_decode_StreamSink_download_progress_update_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<UploadProgressUpdate>
  sse_decode_StreamSink_upload_progress_update_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AuthTokens sse_decode_auth_tokens(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_accessToken = sse_decode_String(deserializer);
    var var_refreshToken = sse_decode_opt_String(deserializer);
    var var_expiresIn = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_idToken = sse_decode_opt_String(deserializer);
    var var_scope = sse_decode_opt_String(deserializer);
    var var_tokenType = sse_decode_opt_String(deserializer);
    return AuthTokens(
      accessToken: var_accessToken,
      refreshToken: var_refreshToken,
      expiresIn: var_expiresIn,
      idToken: var_idToken,
      scope: var_scope,
      tokenType: var_tokenType,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  AuthTokens sse_decode_box_autoadd_auth_tokens(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_auth_tokens(deserializer));
  }

  @protected
  DriveItemSummary sse_decode_box_autoadd_drive_item_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_drive_item_summary(deserializer));
  }

  @protected
  DriveOwner sse_decode_box_autoadd_drive_owner(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_drive_owner(deserializer));
  }

  @protected
  DriveQuota sse_decode_box_autoadd_drive_quota(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_drive_quota(deserializer));
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  StoredAuthState sse_decode_box_autoadd_stored_auth_state(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_stored_auth_state(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  DownloadProgressUpdate sse_decode_download_progress_update(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_itemId = sse_decode_String(deserializer);
    var var_bytesDownloaded = sse_decode_u_64(deserializer);
    var var_expectedSize = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_speedBps = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_timestampMillis = sse_decode_i_64(deserializer);
    return DownloadProgressUpdate(
      itemId: var_itemId,
      bytesDownloaded: var_bytesDownloaded,
      expectedSize: var_expectedSize,
      speedBps: var_speedBps,
      timestampMillis: var_timestampMillis,
    );
  }

  @protected
  DownloadQueueState sse_decode_download_queue_state(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_active = sse_decode_list_download_task(deserializer);
    var var_completed = sse_decode_list_download_task(deserializer);
    var var_failed = sse_decode_list_download_task(deserializer);
    return DownloadQueueState(
      active: var_active,
      completed: var_completed,
      failed: var_failed,
    );
  }

  @protected
  DownloadStatus sse_decode_download_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return DownloadStatus.values[inner];
  }

  @protected
  DownloadTask sse_decode_download_task(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_item = sse_decode_drive_item_summary(deserializer);
    var var_status = sse_decode_download_status(deserializer);
    var var_startedAt = sse_decode_i_64(deserializer);
    var var_completedAt = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_savedPath = sse_decode_opt_String(deserializer);
    var var_sizeLabel = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_bytesDownloaded = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_errorMessage = sse_decode_opt_String(deserializer);
    return DownloadTask(
      item: var_item,
      status: var_status,
      startedAt: var_startedAt,
      completedAt: var_completedAt,
      savedPath: var_savedPath,
      sizeLabel: var_sizeLabel,
      bytesDownloaded: var_bytesDownloaded,
      errorMessage: var_errorMessage,
    );
  }

  @protected
  DriveDownloadResult sse_decode_drive_download_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_fileName = sse_decode_String(deserializer);
    var var_savedPath = sse_decode_String(deserializer);
    var var_bytesDownloaded = sse_decode_u_64(deserializer);
    var var_expectedSize = sse_decode_opt_box_autoadd_u_64(deserializer);
    return DriveDownloadResult(
      fileName: var_fileName,
      savedPath: var_savedPath,
      bytesDownloaded: var_bytesDownloaded,
      expectedSize: var_expectedSize,
    );
  }

  @protected
  DriveInfo sse_decode_drive_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_opt_String(deserializer);
    var var_driveType = sse_decode_opt_String(deserializer);
    var var_owner = sse_decode_opt_box_autoadd_drive_owner(deserializer);
    var var_quota = sse_decode_opt_box_autoadd_drive_quota(deserializer);
    return DriveInfo(
      id: var_id,
      driveType: var_driveType,
      owner: var_owner,
      quota: var_quota,
    );
  }

  @protected
  DriveItemSummary sse_decode_drive_item_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_size = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_isFolder = sse_decode_bool(deserializer);
    var var_childCount = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_mimeType = sse_decode_opt_String(deserializer);
    var var_lastModified = sse_decode_opt_String(deserializer);
    var var_thumbnailUrl = sse_decode_opt_String(deserializer);
    return DriveItemSummary(
      id: var_id,
      name: var_name,
      size: var_size,
      isFolder: var_isFolder,
      childCount: var_childCount,
      mimeType: var_mimeType,
      lastModified: var_lastModified,
      thumbnailUrl: var_thumbnailUrl,
    );
  }

  @protected
  DriveOwner sse_decode_drive_owner(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_displayName = sse_decode_opt_String(deserializer);
    var var_userPrincipalName = sse_decode_opt_String(deserializer);
    var var_id = sse_decode_opt_String(deserializer);
    return DriveOwner(
      displayName: var_displayName,
      userPrincipalName: var_userPrincipalName,
      id: var_id,
    );
  }

  @protected
  DrivePage sse_decode_drive_page(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_items = sse_decode_list_drive_item_summary(deserializer);
    var var_nextLink = sse_decode_opt_String(deserializer);
    return DrivePage(items: var_items, nextLink: var_nextLink);
  }

  @protected
  DriveQuota sse_decode_drive_quota(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_total = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_used = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_remaining = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_deleted = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_state = sse_decode_opt_String(deserializer);
    return DriveQuota(
      total: var_total,
      used: var_used,
      remaining: var_remaining,
      deleted: var_deleted,
      state: var_state,
    );
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<DownloadTask> sse_decode_list_download_task(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DownloadTask>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_download_task(deserializer));
    }
    return ans_;
  }

  @protected
  List<DriveItemSummary> sse_decode_list_drive_item_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DriveItemSummary>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_drive_item_summary(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<UploadTask> sse_decode_list_upload_task(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <UploadTask>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_upload_task(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  DriveOwner? sse_decode_opt_box_autoadd_drive_owner(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_drive_owner(deserializer));
    } else {
      return null;
    }
  }

  @protected
  DriveQuota? sse_decode_opt_box_autoadd_drive_quota(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_drive_quota(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  StoredAuthState? sse_decode_opt_box_autoadd_stored_auth_state(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_stored_auth_state(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  StoredAuthState sse_decode_stored_auth_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_clientId = sse_decode_String(deserializer);
    var var_tokens = sse_decode_auth_tokens(deserializer);
    var var_updatedAtMillis = sse_decode_i_64(deserializer);
    return StoredAuthState(
      clientId: var_clientId,
      tokens: var_tokens,
      updatedAtMillis: var_updatedAtMillis,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  UploadProgressUpdate sse_decode_upload_progress_update(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_taskId = sse_decode_String(deserializer);
    var var_bytesUploaded = sse_decode_u_64(deserializer);
    var var_expectedSize = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_speedBps = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_timestampMillis = sse_decode_i_64(deserializer);
    return UploadProgressUpdate(
      taskId: var_taskId,
      bytesUploaded: var_bytesUploaded,
      expectedSize: var_expectedSize,
      speedBps: var_speedBps,
      timestampMillis: var_timestampMillis,
    );
  }

  @protected
  UploadQueueState sse_decode_upload_queue_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_active = sse_decode_list_upload_task(deserializer);
    var var_completed = sse_decode_list_upload_task(deserializer);
    var var_failed = sse_decode_list_upload_task(deserializer);
    return UploadQueueState(
      active: var_active,
      completed: var_completed,
      failed: var_failed,
    );
  }

  @protected
  UploadStatus sse_decode_upload_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return UploadStatus.values[inner];
  }

  @protected
  UploadTask sse_decode_upload_task(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_taskId = sse_decode_String(deserializer);
    var var_fileName = sse_decode_String(deserializer);
    var var_localPath = sse_decode_String(deserializer);
    var var_size = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_mimeType = sse_decode_opt_String(deserializer);
    var var_parentId = sse_decode_opt_String(deserializer);
    var var_remoteId = sse_decode_opt_String(deserializer);
    var var_status = sse_decode_upload_status(deserializer);
    var var_startedAt = sse_decode_i_64(deserializer);
    var var_completedAt = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_bytesUploaded = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_errorMessage = sse_decode_opt_String(deserializer);
    var var_sessionUrl = sse_decode_opt_String(deserializer);
    return UploadTask(
      taskId: var_taskId,
      fileName: var_fileName,
      localPath: var_localPath,
      size: var_size,
      mimeType: var_mimeType,
      parentId: var_parentId,
      remoteId: var_remoteId,
      status: var_status,
      startedAt: var_startedAt,
      completedAt: var_completedAt,
      bytesUploaded: var_bytesUploaded,
      errorMessage: var_errorMessage,
      sessionUrl: var_sessionUrl,
    );
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_download_progress_update_Sse(
    RustStreamSink<DownloadProgressUpdate> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_download_progress_update,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_upload_progress_update_Sse(
    RustStreamSink<UploadProgressUpdate> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_upload_progress_update,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_auth_tokens(AuthTokens self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.accessToken, serializer);
    sse_encode_opt_String(self.refreshToken, serializer);
    sse_encode_opt_box_autoadd_u_64(self.expiresIn, serializer);
    sse_encode_opt_String(self.idToken, serializer);
    sse_encode_opt_String(self.scope, serializer);
    sse_encode_opt_String(self.tokenType, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_auth_tokens(
    AuthTokens self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_auth_tokens(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_drive_item_summary(
    DriveItemSummary self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_drive_item_summary(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_drive_owner(
    DriveOwner self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_drive_owner(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_drive_quota(
    DriveQuota self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_drive_quota(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_stored_auth_state(
    StoredAuthState self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_stored_auth_state(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_download_progress_update(
    DownloadProgressUpdate self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.itemId, serializer);
    sse_encode_u_64(self.bytesDownloaded, serializer);
    sse_encode_opt_box_autoadd_u_64(self.expectedSize, serializer);
    sse_encode_opt_box_autoadd_f_64(self.speedBps, serializer);
    sse_encode_i_64(self.timestampMillis, serializer);
  }

  @protected
  void sse_encode_download_queue_state(
    DownloadQueueState self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_download_task(self.active, serializer);
    sse_encode_list_download_task(self.completed, serializer);
    sse_encode_list_download_task(self.failed, serializer);
  }

  @protected
  void sse_encode_download_status(
    DownloadStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_download_task(DownloadTask self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_drive_item_summary(self.item, serializer);
    sse_encode_download_status(self.status, serializer);
    sse_encode_i_64(self.startedAt, serializer);
    sse_encode_opt_box_autoadd_i_64(self.completedAt, serializer);
    sse_encode_opt_String(self.savedPath, serializer);
    sse_encode_opt_box_autoadd_u_64(self.sizeLabel, serializer);
    sse_encode_opt_box_autoadd_u_64(self.bytesDownloaded, serializer);
    sse_encode_opt_String(self.errorMessage, serializer);
  }

  @protected
  void sse_encode_drive_download_result(
    DriveDownloadResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.fileName, serializer);
    sse_encode_String(self.savedPath, serializer);
    sse_encode_u_64(self.bytesDownloaded, serializer);
    sse_encode_opt_box_autoadd_u_64(self.expectedSize, serializer);
  }

  @protected
  void sse_encode_drive_info(DriveInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.id, serializer);
    sse_encode_opt_String(self.driveType, serializer);
    sse_encode_opt_box_autoadd_drive_owner(self.owner, serializer);
    sse_encode_opt_box_autoadd_drive_quota(self.quota, serializer);
  }

  @protected
  void sse_encode_drive_item_summary(
    DriveItemSummary self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_opt_box_autoadd_u_64(self.size, serializer);
    sse_encode_bool(self.isFolder, serializer);
    sse_encode_opt_box_autoadd_i_64(self.childCount, serializer);
    sse_encode_opt_String(self.mimeType, serializer);
    sse_encode_opt_String(self.lastModified, serializer);
    sse_encode_opt_String(self.thumbnailUrl, serializer);
  }

  @protected
  void sse_encode_drive_owner(DriveOwner self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.displayName, serializer);
    sse_encode_opt_String(self.userPrincipalName, serializer);
    sse_encode_opt_String(self.id, serializer);
  }

  @protected
  void sse_encode_drive_page(DrivePage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_drive_item_summary(self.items, serializer);
    sse_encode_opt_String(self.nextLink, serializer);
  }

  @protected
  void sse_encode_drive_quota(DriveQuota self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_u_64(self.total, serializer);
    sse_encode_opt_box_autoadd_u_64(self.used, serializer);
    sse_encode_opt_box_autoadd_u_64(self.remaining, serializer);
    sse_encode_opt_box_autoadd_u_64(self.deleted, serializer);
    sse_encode_opt_String(self.state, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_download_task(
    List<DownloadTask> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_download_task(item, serializer);
    }
  }

  @protected
  void sse_encode_list_drive_item_summary(
    List<DriveItemSummary> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_drive_item_summary(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_upload_task(
    List<UploadTask> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_upload_task(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_drive_owner(
    DriveOwner? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_drive_owner(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_drive_quota(
    DriveQuota? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_drive_quota(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_stored_auth_state(
    StoredAuthState? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_stored_auth_state(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_stored_auth_state(
    StoredAuthState self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.clientId, serializer);
    sse_encode_auth_tokens(self.tokens, serializer);
    sse_encode_i_64(self.updatedAtMillis, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_upload_progress_update(
    UploadProgressUpdate self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.taskId, serializer);
    sse_encode_u_64(self.bytesUploaded, serializer);
    sse_encode_opt_box_autoadd_u_64(self.expectedSize, serializer);
    sse_encode_opt_box_autoadd_f_64(self.speedBps, serializer);
    sse_encode_i_64(self.timestampMillis, serializer);
  }

  @protected
  void sse_encode_upload_queue_state(
    UploadQueueState self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_upload_task(self.active, serializer);
    sse_encode_list_upload_task(self.completed, serializer);
    sse_encode_list_upload_task(self.failed, serializer);
  }

  @protected
  void sse_encode_upload_status(UploadStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_upload_task(UploadTask self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.taskId, serializer);
    sse_encode_String(self.fileName, serializer);
    sse_encode_String(self.localPath, serializer);
    sse_encode_opt_box_autoadd_u_64(self.size, serializer);
    sse_encode_opt_String(self.mimeType, serializer);
    sse_encode_opt_String(self.parentId, serializer);
    sse_encode_opt_String(self.remoteId, serializer);
    sse_encode_upload_status(self.status, serializer);
    sse_encode_i_64(self.startedAt, serializer);
    sse_encode_opt_box_autoadd_i_64(self.completedAt, serializer);
    sse_encode_opt_box_autoadd_u_64(self.bytesUploaded, serializer);
    sse_encode_opt_String(self.errorMessage, serializer);
    sse_encode_opt_String(self.sessionUrl, serializer);
  }
}
