// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/auth/auth.dart';
import 'api/auth/refresh.dart';
import 'api/drive/delete.dart';
import 'api/drive/details.dart';
import 'api/drive/download.dart';
import 'api/drive/download_manager.dart';
import 'api/drive/info.dart';
import 'api/drive/list.dart';
import 'api/drive/models.dart';
import 'api/drive/move_item.dart';
import 'api/drive/share.dart';
import 'api/drive/upload.dart';
import 'api/drive/upload_manager.dart';
import 'api/settings/download_concurrency.dart';
import 'api/settings/download_directory.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<DownloadProgressUpdate>
  dco_decode_StreamSink_download_progress_update_Sse(dynamic raw);

  @protected
  RustStreamSink<UploadProgressUpdate>
  dco_decode_StreamSink_upload_progress_update_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AuthTokens dco_decode_auth_tokens(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AuthTokens dco_decode_box_autoadd_auth_tokens(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  DriveItemSummary dco_decode_box_autoadd_drive_item_summary(dynamic raw);

  @protected
  DriveOwner dco_decode_box_autoadd_drive_owner(dynamic raw);

  @protected
  DriveQuota dco_decode_box_autoadd_drive_quota(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  StoredAuthState dco_decode_box_autoadd_stored_auth_state(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  DownloadProgressUpdate dco_decode_download_progress_update(dynamic raw);

  @protected
  DownloadQueueState dco_decode_download_queue_state(dynamic raw);

  @protected
  DownloadStatus dco_decode_download_status(dynamic raw);

  @protected
  DownloadTask dco_decode_download_task(dynamic raw);

  @protected
  DriveDownloadResult dco_decode_drive_download_result(dynamic raw);

  @protected
  DriveInfo dco_decode_drive_info(dynamic raw);

  @protected
  DriveItemDetails dco_decode_drive_item_details(dynamic raw);

  @protected
  DriveItemSummary dco_decode_drive_item_summary(dynamic raw);

  @protected
  DriveOwner dco_decode_drive_owner(dynamic raw);

  @protected
  DrivePage dco_decode_drive_page(dynamic raw);

  @protected
  DriveQuota dco_decode_drive_quota(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  LinkScope dco_decode_link_scope(dynamic raw);

  @protected
  LinkType dco_decode_link_type(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<DownloadTask> dco_decode_list_download_task(dynamic raw);

  @protected
  List<DriveItemSummary> dco_decode_list_drive_item_summary(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<UploadTask> dco_decode_list_upload_task(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  DriveOwner? dco_decode_opt_box_autoadd_drive_owner(dynamic raw);

  @protected
  DriveQuota? dco_decode_opt_box_autoadd_drive_quota(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  StoredAuthState? dco_decode_opt_box_autoadd_stored_auth_state(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  ShareCapabilities dco_decode_share_capabilities(dynamic raw);

  @protected
  ShareLinkResult dco_decode_share_link_result(dynamic raw);

  @protected
  StoredAuthState dco_decode_stored_auth_state(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UploadProgressUpdate dco_decode_upload_progress_update(dynamic raw);

  @protected
  UploadQueueState dco_decode_upload_queue_state(dynamic raw);

  @protected
  UploadStatus dco_decode_upload_status(dynamic raw);

  @protected
  UploadTask dco_decode_upload_task(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<DownloadProgressUpdate>
  sse_decode_StreamSink_download_progress_update_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<UploadProgressUpdate>
  sse_decode_StreamSink_upload_progress_update_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AuthTokens sse_decode_auth_tokens(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AuthTokens sse_decode_box_autoadd_auth_tokens(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  DriveItemSummary sse_decode_box_autoadd_drive_item_summary(
    SseDeserializer deserializer,
  );

  @protected
  DriveOwner sse_decode_box_autoadd_drive_owner(SseDeserializer deserializer);

  @protected
  DriveQuota sse_decode_box_autoadd_drive_quota(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  StoredAuthState sse_decode_box_autoadd_stored_auth_state(
    SseDeserializer deserializer,
  );

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  DownloadProgressUpdate sse_decode_download_progress_update(
    SseDeserializer deserializer,
  );

  @protected
  DownloadQueueState sse_decode_download_queue_state(
    SseDeserializer deserializer,
  );

  @protected
  DownloadStatus sse_decode_download_status(SseDeserializer deserializer);

  @protected
  DownloadTask sse_decode_download_task(SseDeserializer deserializer);

  @protected
  DriveDownloadResult sse_decode_drive_download_result(
    SseDeserializer deserializer,
  );

  @protected
  DriveInfo sse_decode_drive_info(SseDeserializer deserializer);

  @protected
  DriveItemDetails sse_decode_drive_item_details(SseDeserializer deserializer);

  @protected
  DriveItemSummary sse_decode_drive_item_summary(SseDeserializer deserializer);

  @protected
  DriveOwner sse_decode_drive_owner(SseDeserializer deserializer);

  @protected
  DrivePage sse_decode_drive_page(SseDeserializer deserializer);

  @protected
  DriveQuota sse_decode_drive_quota(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  LinkScope sse_decode_link_scope(SseDeserializer deserializer);

  @protected
  LinkType sse_decode_link_type(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<DownloadTask> sse_decode_list_download_task(
    SseDeserializer deserializer,
  );

  @protected
  List<DriveItemSummary> sse_decode_list_drive_item_summary(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<UploadTask> sse_decode_list_upload_task(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  DriveOwner? sse_decode_opt_box_autoadd_drive_owner(
    SseDeserializer deserializer,
  );

  @protected
  DriveQuota? sse_decode_opt_box_autoadd_drive_quota(
    SseDeserializer deserializer,
  );

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  StoredAuthState? sse_decode_opt_box_autoadd_stored_auth_state(
    SseDeserializer deserializer,
  );

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  ShareCapabilities sse_decode_share_capabilities(SseDeserializer deserializer);

  @protected
  ShareLinkResult sse_decode_share_link_result(SseDeserializer deserializer);

  @protected
  StoredAuthState sse_decode_stored_auth_state(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UploadProgressUpdate sse_decode_upload_progress_update(
    SseDeserializer deserializer,
  );

  @protected
  UploadQueueState sse_decode_upload_queue_state(SseDeserializer deserializer);

  @protected
  UploadStatus sse_decode_upload_status(SseDeserializer deserializer);

  @protected
  UploadTask sse_decode_upload_task(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_download_progress_update_Sse(
    RustStreamSink<DownloadProgressUpdate> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_upload_progress_update_Sse(
    RustStreamSink<UploadProgressUpdate> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_auth_tokens(AuthTokens self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_auth_tokens(
    AuthTokens self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_drive_item_summary(
    DriveItemSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_drive_owner(
    DriveOwner self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_drive_quota(
    DriveQuota self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_stored_auth_state(
    StoredAuthState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_download_progress_update(
    DownloadProgressUpdate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_download_queue_state(
    DownloadQueueState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_download_status(
    DownloadStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_download_task(DownloadTask self, SseSerializer serializer);

  @protected
  void sse_encode_drive_download_result(
    DriveDownloadResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_drive_info(DriveInfo self, SseSerializer serializer);

  @protected
  void sse_encode_drive_item_details(
    DriveItemDetails self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_drive_item_summary(
    DriveItemSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_drive_owner(DriveOwner self, SseSerializer serializer);

  @protected
  void sse_encode_drive_page(DrivePage self, SseSerializer serializer);

  @protected
  void sse_encode_drive_quota(DriveQuota self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_link_scope(LinkScope self, SseSerializer serializer);

  @protected
  void sse_encode_link_type(LinkType self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_download_task(
    List<DownloadTask> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_drive_item_summary(
    List<DriveItemSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_upload_task(
    List<UploadTask> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_drive_owner(
    DriveOwner? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_drive_quota(
    DriveQuota? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_stored_auth_state(
    StoredAuthState? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_share_capabilities(
    ShareCapabilities self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_share_link_result(
    ShareLinkResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_stored_auth_state(
    StoredAuthState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_upload_progress_update(
    UploadProgressUpdate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_upload_queue_state(
    UploadQueueState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_upload_status(UploadStatus self, SseSerializer serializer);

  @protected
  void sse_encode_upload_task(UploadTask self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
