// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// FRB 对外接口：获取当前并行下载数设置。
Future<int> getDownloadConcurrency() => RustLib.instance.api
    .crateApiSettingsDownloadConcurrencyGetDownloadConcurrency();

/// FRB 对外接口：更新并行下载数，并立即通知下载管理器生效。
Future<int> setDownloadConcurrency({required int limit}) => RustLib.instance.api
    .crateApiSettingsDownloadConcurrencySetDownloadConcurrency(limit: limit);
