// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// FRB 对外接口：读取“是否启用离线索引”开关。
Future<bool> getOfflineIndexEnabled() =>
    RustLib.instance.api.crateApiSettingsOfflineIndexGetOfflineIndexEnabled();

/// FRB 对外接口：更新“是否启用离线索引”开关。
Future<bool> setOfflineIndexEnabled({required bool value}) => RustLib
    .instance
    .api
    .crateApiSettingsOfflineIndexSetOfflineIndexEnabled(value: value);
