// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// FRB 对外接口：获取是否跟随系统主题。
Future<bool> getThemeFollowSystem() =>
    RustLib.instance.api.crateApiSettingsThemeGetThemeFollowSystem();

/// FRB 对外接口：设置是否跟随系统主题。
Future<bool> setThemeFollowSystem({required bool value}) => RustLib.instance.api
    .crateApiSettingsThemeSetThemeFollowSystem(value: value);

/// FRB 对外接口：获取手动主题模式（light/dark）。
Future<String> getThemeManualMode() =>
    RustLib.instance.api.crateApiSettingsThemeGetThemeManualMode();

/// FRB 对外接口：设置手动主题模式（light/dark）。
Future<String> setThemeManualMode({required String mode}) =>
    RustLib.instance.api.crateApiSettingsThemeSetThemeManualMode(mode: mode);
